[env:xiaoblesense_adafruit]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense_adafruit
framework = arduino
lib_deps =
	adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/Adafruit SHARP Memory Display @ ^1.1.1
	adafruit/Adafruit BMP280 Library @ ^2.6.8
build_flags =
	-D MOCK_MODE=1
